language: python
python:
  - "2.6"
  - "2.7"
before_script: 
  - sudo apt-get install pychecker pylint pep8 python-yaml rpm python-rpm
install:
  - sudo mkdir /var/log/yadtshell
  - sudo chmod 777 /var/log/yadtshell
  - pip install -r requirements.txt --use-mirrors
script: "pyb --debug"
notifications:
  email:
    - michael.gruber@immobilienscout24.de
    - arne.hilmann@immobilienscout24.de

