language: python
python:
  - "2.6"
  - "2.7"
before_script:
  - sudo apt-get install pychecker pylint pep8 rpm python-rpm ruby-ronn
  - sudo mkdir /var/log/yadtshell
  - sudo chmod 777 /var/log/yadtshell
install:
  - pip install pybuilder
  - pyb --debug install_dependencies
script: "pyb --debug publish"
notifications:
  email:
    - arne.hilmann@immobilienscout24.de
    - michael.gruber@immobilienscout24.de
    - maximilien.riehl@immobilienscout24.de
