language: python
python:
    - "2.6"
    - "2.7"
before_script:
    - sudo apt-get install python-coverage
    - sudo apt-get install pychecker
    - sudo apt-get install pymetrics
    - sudo apt-get install python-setuptools
    - sudo apt-get install pylint
    - sudo easy_install https://github.com/downloads/pybuilder/pybuilder/pybuilder-0.6.4.tar.gz 
    - sudo easy_install https://github.com/downloads/yadt/hostexpand/hostexpand-1.0.1.tar.gz
    - sudo easy_install https://github.com/downloads/yadt/shtub/shtub-0.2.4.tar.gz
    - sudo apt-get install python-yaml
    - sudo apt-get install python-twisted
    - sudo apt-get install rpm
    - sudo apt-get install python-rpm
    - sudo mkdir /var/log/yadtshell
    - sudo chmod 777 /var/log/yadtshell
script: "pyb"
notifications:
  email:
    - michael.gruber@immobilienscout24.de
    - arne.hilmann@immobilienscout24.de
